name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [machine-learning-client, web-app]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify the Python version you need

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      working-directory: ./${{ matrix.service }}
      run: |
        pipenv install --dev

    - name: Run linting
      working-directory: ./${{ matrix.service }}
      run: |
        if [ "${{ matrix.service }}" == "machine-learning-client" ]; then
          pipenv run pylint src/main.py
        elif [ "${{ matrix.service }}" == "web-app" ]; then
          pipenv run pylint app.py
        fi
    - name: Format code with Black
      working-directory: ./${{ matrix.service }}
      run: pipenv run black .
    - name: Run tests
      working-directory: ./${{ matrix.service }}
      run: |
        pipenv run pytest